# Generated by Django 5.0.6 on 2024-06-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='num',
            field=models.BigIntegerField(unique=True, verbose_name='Account number'),
        ),
    ]
