# Generated by Django 5.0.6 on 2024-06-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_wallet_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='card',
            field=models.BigIntegerField(unique=True, verbose_name='Card number'),
        ),
    ]
