# Generated by Django 5.0.6 on 2024-06-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_wallet_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='e_wallet',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='favourite',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='banks',
            field=models.ManyToManyField(related_name='banks', to='api.wallet'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='e_wallets',
            field=models.ManyToManyField(related_name='e_wallets', to='api.wallet'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='api.wallet'),
        ),
    ]
