# Generated by Django 5.0.6 on 2024-06-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_beneficiary_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
