# Generated by Django 5.0.6 on 2024-06-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_beneficiary_bank_remove_beneficiary_e_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.CharField(default='World Bank', max_length=50),
        ),
    ]
