# Generated by Django 5.0.6 on 2024-06-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_reciever_transaction_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debits', to='api.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='api.wallet'),
        ),
    ]
